services:
  backend:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: casino_backend
    restart: always
    env_file:
      - ./../.env
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - ./../:/app
    command: /bin/bash -lc "cd /app && bun install && bun run dev:back"

  frontend:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: casino_frontend
    restart: always
    env_file:
      - ./../.env
    ports:
      - '80:3157'
    volumes:
      - ./../:/app
    command: /bin/bash -lc "cd /app && bun install && cd app/frontend && bun run build ; bun run serve"

  mysql:
    image: mysql:8.0
    container_name: casino_mysql
    ports:
      - '3306:3306'
    restart: always
    env_file:
      - ./../.env
    environment:
      - TZ="Asia/Tokyo"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/mysql_data:/var/lib/mysql
