/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as CheckinRouteRouteImport } from './routes/checkin/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminSaleRouteRouteImport } from './routes/admin/sale/route'
import { Route as AdminCustomerRouteRouteImport } from './routes/admin/customer/route'
import { Route as AdminCheckoutRouteRouteImport } from './routes/admin/checkout/route'
import { Route as AdminCheckinRouteRouteImport } from './routes/admin/checkin/route'
import { Route as UsersLoginIndexRouteImport } from './routes/users/login/index'
import { Route as AdminCheckoutUserIdRouteRouteImport } from './routes/admin/checkout/$userId/route'

const CheckinIndexLazyRouteImport = createFileRoute('/checkin/')()
const AdminIndexLazyRouteImport = createFileRoute('/admin/')()
const UsersUserIdIndexLazyRouteImport = createFileRoute('/users/$userId/')()
const CheckinRepeatIndexLazyRouteImport = createFileRoute('/checkin/repeat/')()
const CheckinFirstIndexLazyRouteImport = createFileRoute('/checkin/first/')()
const CheckinUserIdIndexLazyRouteImport = createFileRoute('/checkin/$userId/')()
const AdminSaleIndexLazyRouteImport = createFileRoute('/admin/sale/')()
const AdminCustomerIndexLazyRouteImport = createFileRoute('/admin/customer/')()
const AdminCheckoutIndexLazyRouteImport = createFileRoute('/admin/checkout/')()
const AdminCheckinIndexLazyRouteImport = createFileRoute('/admin/checkin/')()
const AdminCheckoutUserIdIndexLazyRouteImport = createFileRoute(
  '/admin/checkout/$userId/',
)()

const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRouteRoute = CheckinRouteRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinIndexLazyRoute = CheckinIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckinRouteRoute,
} as any).lazy(() => import('./routes/checkin/index.lazy').then((d) => d.Route))
const AdminIndexLazyRoute = AdminIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const AdminSaleRouteRoute = AdminSaleRouteRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomerRouteRoute = AdminCustomerRouteRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCheckoutRouteRoute = AdminCheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCheckinRouteRoute = AdminCheckinRouteRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UsersUserIdIndexLazyRoute = UsersUserIdIndexLazyRouteImport.update({
  id: '/$userId/',
  path: '/$userId/',
  getParentRoute: () => UsersRouteRoute,
} as any).lazy(() =>
  import('./routes/users/$userId/index.lazy').then((d) => d.Route),
)
const CheckinRepeatIndexLazyRoute = CheckinRepeatIndexLazyRouteImport.update({
  id: '/repeat/',
  path: '/repeat/',
  getParentRoute: () => CheckinRouteRoute,
} as any).lazy(() =>
  import('./routes/checkin/repeat/index.lazy').then((d) => d.Route),
)
const CheckinFirstIndexLazyRoute = CheckinFirstIndexLazyRouteImport.update({
  id: '/first/',
  path: '/first/',
  getParentRoute: () => CheckinRouteRoute,
} as any).lazy(() =>
  import('./routes/checkin/first/index.lazy').then((d) => d.Route),
)
const CheckinUserIdIndexLazyRoute = CheckinUserIdIndexLazyRouteImport.update({
  id: '/$userId/',
  path: '/$userId/',
  getParentRoute: () => CheckinRouteRoute,
} as any).lazy(() =>
  import('./routes/checkin/$userId/index.lazy').then((d) => d.Route),
)
const AdminSaleIndexLazyRoute = AdminSaleIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSaleRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/sale/index.lazy').then((d) => d.Route),
)
const AdminCustomerIndexLazyRoute = AdminCustomerIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCustomerRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/customer/index.lazy').then((d) => d.Route),
)
const AdminCheckoutIndexLazyRoute = AdminCheckoutIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCheckoutRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/checkout/index.lazy').then((d) => d.Route),
)
const AdminCheckinIndexLazyRoute = AdminCheckinIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCheckinRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/checkin/index.lazy').then((d) => d.Route),
)
const UsersLoginIndexRoute = UsersLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const AdminCheckoutUserIdRouteRoute =
  AdminCheckoutUserIdRouteRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AdminCheckoutRouteRoute,
  } as any)
const AdminCheckoutUserIdIndexLazyRoute =
  AdminCheckoutUserIdIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCheckoutUserIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/admin/checkout/$userId/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/checkin': typeof CheckinRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/admin/checkin': typeof AdminCheckinRouteRouteWithChildren
  '/admin/checkout': typeof AdminCheckoutRouteRouteWithChildren
  '/admin/customer': typeof AdminCustomerRouteRouteWithChildren
  '/admin/sale': typeof AdminSaleRouteRouteWithChildren
  '/admin/': typeof AdminIndexLazyRoute
  '/checkin/': typeof CheckinIndexLazyRoute
  '/admin/checkout/$userId': typeof AdminCheckoutUserIdRouteRouteWithChildren
  '/users/login': typeof UsersLoginIndexRoute
  '/admin/checkin/': typeof AdminCheckinIndexLazyRoute
  '/admin/checkout/': typeof AdminCheckoutIndexLazyRoute
  '/admin/customer/': typeof AdminCustomerIndexLazyRoute
  '/admin/sale/': typeof AdminSaleIndexLazyRoute
  '/checkin/$userId': typeof CheckinUserIdIndexLazyRoute
  '/checkin/first': typeof CheckinFirstIndexLazyRoute
  '/checkin/repeat': typeof CheckinRepeatIndexLazyRoute
  '/users/$userId': typeof UsersUserIdIndexLazyRoute
  '/admin/checkout/$userId/': typeof AdminCheckoutUserIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/users': typeof UsersRouteRouteWithChildren
  '/admin': typeof AdminIndexLazyRoute
  '/checkin': typeof CheckinIndexLazyRoute
  '/users/login': typeof UsersLoginIndexRoute
  '/admin/checkin': typeof AdminCheckinIndexLazyRoute
  '/admin/checkout': typeof AdminCheckoutIndexLazyRoute
  '/admin/customer': typeof AdminCustomerIndexLazyRoute
  '/admin/sale': typeof AdminSaleIndexLazyRoute
  '/checkin/$userId': typeof CheckinUserIdIndexLazyRoute
  '/checkin/first': typeof CheckinFirstIndexLazyRoute
  '/checkin/repeat': typeof CheckinRepeatIndexLazyRoute
  '/users/$userId': typeof UsersUserIdIndexLazyRoute
  '/admin/checkout/$userId': typeof AdminCheckoutUserIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/checkin': typeof CheckinRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/admin/checkin': typeof AdminCheckinRouteRouteWithChildren
  '/admin/checkout': typeof AdminCheckoutRouteRouteWithChildren
  '/admin/customer': typeof AdminCustomerRouteRouteWithChildren
  '/admin/sale': typeof AdminSaleRouteRouteWithChildren
  '/admin/': typeof AdminIndexLazyRoute
  '/checkin/': typeof CheckinIndexLazyRoute
  '/admin/checkout/$userId': typeof AdminCheckoutUserIdRouteRouteWithChildren
  '/users/login/': typeof UsersLoginIndexRoute
  '/admin/checkin/': typeof AdminCheckinIndexLazyRoute
  '/admin/checkout/': typeof AdminCheckoutIndexLazyRoute
  '/admin/customer/': typeof AdminCustomerIndexLazyRoute
  '/admin/sale/': typeof AdminSaleIndexLazyRoute
  '/checkin/$userId/': typeof CheckinUserIdIndexLazyRoute
  '/checkin/first/': typeof CheckinFirstIndexLazyRoute
  '/checkin/repeat/': typeof CheckinRepeatIndexLazyRoute
  '/users/$userId/': typeof UsersUserIdIndexLazyRoute
  '/admin/checkout/$userId/': typeof AdminCheckoutUserIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/checkin'
    | '/users'
    | '/admin/checkin'
    | '/admin/checkout'
    | '/admin/customer'
    | '/admin/sale'
    | '/admin/'
    | '/checkin/'
    | '/admin/checkout/$userId'
    | '/users/login'
    | '/admin/checkin/'
    | '/admin/checkout/'
    | '/admin/customer/'
    | '/admin/sale/'
    | '/checkin/$userId'
    | '/checkin/first'
    | '/checkin/repeat'
    | '/users/$userId'
    | '/admin/checkout/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/users'
    | '/admin'
    | '/checkin'
    | '/users/login'
    | '/admin/checkin'
    | '/admin/checkout'
    | '/admin/customer'
    | '/admin/sale'
    | '/checkin/$userId'
    | '/checkin/first'
    | '/checkin/repeat'
    | '/users/$userId'
    | '/admin/checkout/$userId'
  id:
    | '__root__'
    | '/admin'
    | '/checkin'
    | '/users'
    | '/admin/checkin'
    | '/admin/checkout'
    | '/admin/customer'
    | '/admin/sale'
    | '/admin/'
    | '/checkin/'
    | '/admin/checkout/$userId'
    | '/users/login/'
    | '/admin/checkin/'
    | '/admin/checkout/'
    | '/admin/customer/'
    | '/admin/sale/'
    | '/checkin/$userId/'
    | '/checkin/first/'
    | '/checkin/repeat/'
    | '/users/$userId/'
    | '/admin/checkout/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CheckinRouteRoute: typeof CheckinRouteRouteWithChildren
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/': {
      id: '/checkin/'
      path: '/'
      fullPath: '/checkin/'
      preLoaderRoute: typeof CheckinIndexLazyRouteImport
      parentRoute: typeof CheckinRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sale': {
      id: '/admin/sale'
      path: '/sale'
      fullPath: '/admin/sale'
      preLoaderRoute: typeof AdminSaleRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customer': {
      id: '/admin/customer'
      path: '/customer'
      fullPath: '/admin/customer'
      preLoaderRoute: typeof AdminCustomerRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/checkout': {
      id: '/admin/checkout'
      path: '/checkout'
      fullPath: '/admin/checkout'
      preLoaderRoute: typeof AdminCheckoutRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdIndexLazyRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/checkin/repeat/': {
      id: '/checkin/repeat/'
      path: '/repeat'
      fullPath: '/checkin/repeat'
      preLoaderRoute: typeof CheckinRepeatIndexLazyRouteImport
      parentRoute: typeof CheckinRouteRoute
    }
    '/checkin/first/': {
      id: '/checkin/first/'
      path: '/first'
      fullPath: '/checkin/first'
      preLoaderRoute: typeof CheckinFirstIndexLazyRouteImport
      parentRoute: typeof CheckinRouteRoute
    }
    '/checkin/$userId/': {
      id: '/checkin/$userId/'
      path: '/$userId'
      fullPath: '/checkin/$userId'
      preLoaderRoute: typeof CheckinUserIdIndexLazyRouteImport
      parentRoute: typeof CheckinRouteRoute
    }
    '/admin/sale/': {
      id: '/admin/sale/'
      path: '/'
      fullPath: '/admin/sale/'
      preLoaderRoute: typeof AdminSaleIndexLazyRouteImport
      parentRoute: typeof AdminSaleRouteRoute
    }
    '/admin/customer/': {
      id: '/admin/customer/'
      path: '/'
      fullPath: '/admin/customer/'
      preLoaderRoute: typeof AdminCustomerIndexLazyRouteImport
      parentRoute: typeof AdminCustomerRouteRoute
    }
    '/admin/checkout/': {
      id: '/admin/checkout/'
      path: '/'
      fullPath: '/admin/checkout/'
      preLoaderRoute: typeof AdminCheckoutIndexLazyRouteImport
      parentRoute: typeof AdminCheckoutRouteRoute
    }
    '/admin/checkin/': {
      id: '/admin/checkin/'
      path: '/'
      fullPath: '/admin/checkin/'
      preLoaderRoute: typeof AdminCheckinIndexLazyRouteImport
      parentRoute: typeof AdminCheckinRouteRoute
    }
    '/users/login/': {
      id: '/users/login/'
      path: '/login'
      fullPath: '/users/login'
      preLoaderRoute: typeof UsersLoginIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/admin/checkout/$userId': {
      id: '/admin/checkout/$userId'
      path: '/$userId'
      fullPath: '/admin/checkout/$userId'
      preLoaderRoute: typeof AdminCheckoutUserIdRouteRouteImport
      parentRoute: typeof AdminCheckoutRouteRoute
    }
    '/admin/checkout/$userId/': {
      id: '/admin/checkout/$userId/'
      path: '/'
      fullPath: '/admin/checkout/$userId/'
      preLoaderRoute: typeof AdminCheckoutUserIdIndexLazyRouteImport
      parentRoute: typeof AdminCheckoutUserIdRouteRoute
    }
  }
}

interface AdminCheckinRouteRouteChildren {
  AdminCheckinIndexLazyRoute: typeof AdminCheckinIndexLazyRoute
}

const AdminCheckinRouteRouteChildren: AdminCheckinRouteRouteChildren = {
  AdminCheckinIndexLazyRoute: AdminCheckinIndexLazyRoute,
}

const AdminCheckinRouteRouteWithChildren =
  AdminCheckinRouteRoute._addFileChildren(AdminCheckinRouteRouteChildren)

interface AdminCheckoutUserIdRouteRouteChildren {
  AdminCheckoutUserIdIndexLazyRoute: typeof AdminCheckoutUserIdIndexLazyRoute
}

const AdminCheckoutUserIdRouteRouteChildren: AdminCheckoutUserIdRouteRouteChildren =
  {
    AdminCheckoutUserIdIndexLazyRoute: AdminCheckoutUserIdIndexLazyRoute,
  }

const AdminCheckoutUserIdRouteRouteWithChildren =
  AdminCheckoutUserIdRouteRoute._addFileChildren(
    AdminCheckoutUserIdRouteRouteChildren,
  )

interface AdminCheckoutRouteRouteChildren {
  AdminCheckoutUserIdRouteRoute: typeof AdminCheckoutUserIdRouteRouteWithChildren
  AdminCheckoutIndexLazyRoute: typeof AdminCheckoutIndexLazyRoute
}

const AdminCheckoutRouteRouteChildren: AdminCheckoutRouteRouteChildren = {
  AdminCheckoutUserIdRouteRoute: AdminCheckoutUserIdRouteRouteWithChildren,
  AdminCheckoutIndexLazyRoute: AdminCheckoutIndexLazyRoute,
}

const AdminCheckoutRouteRouteWithChildren =
  AdminCheckoutRouteRoute._addFileChildren(AdminCheckoutRouteRouteChildren)

interface AdminCustomerRouteRouteChildren {
  AdminCustomerIndexLazyRoute: typeof AdminCustomerIndexLazyRoute
}

const AdminCustomerRouteRouteChildren: AdminCustomerRouteRouteChildren = {
  AdminCustomerIndexLazyRoute: AdminCustomerIndexLazyRoute,
}

const AdminCustomerRouteRouteWithChildren =
  AdminCustomerRouteRoute._addFileChildren(AdminCustomerRouteRouteChildren)

interface AdminSaleRouteRouteChildren {
  AdminSaleIndexLazyRoute: typeof AdminSaleIndexLazyRoute
}

const AdminSaleRouteRouteChildren: AdminSaleRouteRouteChildren = {
  AdminSaleIndexLazyRoute: AdminSaleIndexLazyRoute,
}

const AdminSaleRouteRouteWithChildren = AdminSaleRouteRoute._addFileChildren(
  AdminSaleRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCheckinRouteRoute: typeof AdminCheckinRouteRouteWithChildren
  AdminCheckoutRouteRoute: typeof AdminCheckoutRouteRouteWithChildren
  AdminCustomerRouteRoute: typeof AdminCustomerRouteRouteWithChildren
  AdminSaleRouteRoute: typeof AdminSaleRouteRouteWithChildren
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCheckinRouteRoute: AdminCheckinRouteRouteWithChildren,
  AdminCheckoutRouteRoute: AdminCheckoutRouteRouteWithChildren,
  AdminCustomerRouteRoute: AdminCustomerRouteRouteWithChildren,
  AdminSaleRouteRoute: AdminSaleRouteRouteWithChildren,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CheckinRouteRouteChildren {
  CheckinIndexLazyRoute: typeof CheckinIndexLazyRoute
  CheckinUserIdIndexLazyRoute: typeof CheckinUserIdIndexLazyRoute
  CheckinFirstIndexLazyRoute: typeof CheckinFirstIndexLazyRoute
  CheckinRepeatIndexLazyRoute: typeof CheckinRepeatIndexLazyRoute
}

const CheckinRouteRouteChildren: CheckinRouteRouteChildren = {
  CheckinIndexLazyRoute: CheckinIndexLazyRoute,
  CheckinUserIdIndexLazyRoute: CheckinUserIdIndexLazyRoute,
  CheckinFirstIndexLazyRoute: CheckinFirstIndexLazyRoute,
  CheckinRepeatIndexLazyRoute: CheckinRepeatIndexLazyRoute,
}

const CheckinRouteRouteWithChildren = CheckinRouteRoute._addFileChildren(
  CheckinRouteRouteChildren,
)

interface UsersRouteRouteChildren {
  UsersLoginIndexRoute: typeof UsersLoginIndexRoute
  UsersUserIdIndexLazyRoute: typeof UsersUserIdIndexLazyRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersLoginIndexRoute: UsersLoginIndexRoute,
  UsersUserIdIndexLazyRoute: UsersUserIdIndexLazyRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CheckinRouteRoute: CheckinRouteRouteWithChildren,
  UsersRouteRoute: UsersRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
